name: CI/CD Manually
on: [workflow_dispatch]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: yarn install

      - name: Install browsers for Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: yarn test
